# Generated by Django 2.0.9 on 2018-11-06 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=16),
        ),
    ]
