# Generated by Django 2.0.9 on 2018-11-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clubee', '0002_auto_20181106_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='categoria',
            field=models.CharField(default='Club', max_length=255),
        ),
    ]
